import slugify from '../utils/slugify'
import { FiUser } from 'react-icons/fi'

export default {
  title: "Work",
  name: 'work',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this release",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: 'Release date',
      name: 'releaseDate',
      type: 'date'
    },
    {
      title: 'Category',
      name: 'category',
      type: 'string',
      initialValue: 'project',
      options: {
        list: [
          { title: 'Project', value: 'project' },
          { title: 'Case Study', value: 'story' },
        ],
      },
    },
    {
      title: 'Tech Stack',
      name: 'stack',
      description: 'Technology used for the project',
      type: 'array', 
      of: [{
        title: 'Technology',
        name: 'tech',
        type: 'object',
        icon: FiUser,
        fields: [
          {
            title: 'Title',
            name: 'title',
            type: 'string',
            description: 'eg: "Next"',
          },
          {
            title: 'Type',
            name: 'type',
            type: 'string',
            description: 'eg: "Static Site Generator"',
          },
        ],
        preview: {
          select: {
            title: 'title',
            subtitle: 'type'
          }
        }
      }],
    },
    {
      title: 'Thumbnail',
      name: 'thumbnail',
      type: 'defaultImage',
      description: 'The main image used on the home page',
      validation: Rule => Rule.required()
    },
    {
      title: 'Logo',
      name: 'logo',
      type: 'defaultImage',
      description: 'The main image used on the home page',
      validation: Rule => Rule.required()
    },
    {
      title: 'Main Image',
      name: 'image',
      type: 'defaultImage',
      description: 'The main image used in the project',
      validation: Rule => Rule.required()
    },
    {
      title: 'Background color',
      name: 'bgColor',
      type: 'color'
    },
    {
      title: 'Content Blocks',
      name: 'contentBlocks',
      description: 'The modular content blocks for this project',
      type: 'array',
      of: [
        {type: 'modularImageBlock', title: 'Single Image'},
        {type: 'textBlock', title: 'Text'},
        {type: 'imageCarouselBlock', title: 'Image Carousel'},
        {type: 'collectionGridBlock', title: 'Collection Grid'},
        {type: 'modularImageTextBlock', title: 'Image + Text'},
        {type: 'modularDoubleImageBlock', title: 'Double Image'},
        {type: 'modularSideBySideImageBlock', title: 'Side By Side Portrait Image'},
      ],
    },
    {
      title: 'Credits',
      name: 'credits',
      description: 'Credits for this project',
      type: 'array', 
      of: [{
        title: 'Credit',
        name: 'credit',
        type: 'object',
        icon: FiUser,
        fields: [
          {
            title: 'Job',
            name: 'job',
            type: 'string',
            description: 'eg: "Set & Styling", "Props / Set Asst',
            validation: Rule => Rule.required()
          },
          {
            title: 'Name',
            name: 'name',
            type: 'string',
            description: 'eg: "Oliver Blackburn"',
            validation: Rule => Rule.required()
          },
        ],
        preview: {
          select: {
            title: 'job',
            subtitle: 'name'
          }
        }
      }],
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = ''
          if (doc.title) {
            titleSlug = `${doc.title}`
          } else {
            titleSlug = ''
          }

          return `${titleSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  orderings: [
    {
      title: "Title",
      name: "title",
      by: [{ field: "releaseDate", direction: "asc" }],
    },
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'campaignTitle',
      media: 'thumbnail'
    }
  }
}